const completeProjects=[
  {id:'PJ-260718',name:'星河制造数据平台',customer:'星河制造',type:'AI定制开发',owner:'陈浩',cycle:'06-18 至 09-30',progress:68,health:'高风险',stage:'系统联调',baseline:'V2 · 07-18生效',hours:'326 / 480h',risks:3},
  {id:'PJ-260717',name:'北辰零售账号矩阵',customer:'北辰零售',type:'自媒体代运营',owner:'林溪',cycle:'07-01 至 12-31',progress:42,health:'正常',stage:'7月内容复盘',baseline:'V1 · 07-01生效',hours:'168 / 420h',risks:1},
  {id:'PJ-260716',name:'嘉禾教育AI培训',customer:'嘉禾教育',type:'AI产品销售',owner:'周启明',cycle:'07-15 至 08-08',progress:54,health:'需关注',stage:'讲师试讲',baseline:'V1 · 07-15生效',hours:'42 / 80h',risks:1},
  {id:'PJ-260715',name:'瑞景文旅智能客服',customer:'瑞景文旅',type:'AI定制开发',owner:'许哲',cycle:'05-20 至 08-20',progress:83,health:'正常',stage:'用户验收',baseline:'V2 · 07-10生效',hours:'392 / 460h',risks:1}
];
Object.assign(state,{projectDetailIndex:null,projectDetailTab:'overview',projectDetailProgress:{}});

function currentCompleteProject(){const p=completeProjects[state.projectDetailIndex??0];return {...p,progress:state.projectDetailProgress[state.projectDetailIndex]??p.progress}}
function detailKpis(p){return `<section class="project-detail-kpis"><article class="project-detail-kpi"><small>证据化进度</small><strong>${p.progress}%</strong><span>由任务、交付物与验收计算</span></article><article class="project-detail-kpi"><small>当前阶段</small><strong style="font-size:19px">${p.stage}</strong><span>下一节点 07-28</span></article><article class="project-detail-kpi"><small>计划 / 实际工时</small><strong style="font-size:19px">${p.hours}</strong><span>实际工时来自员工填报</span></article><article class="project-detail-kpi"><small>未关闭风险</small><strong>${p.risks}</strong><span>${p.risks>2?'需要负责人介入':'均已指定责任人'}</span></article><article class="project-detail-kpi"><small>内部验收</small><strong style="font-size:19px">待组织</strong><span>交付物完成 16 / 18</span></article></section>`}
function projectDetailOverview(p){return `<div class="project-detail-grid"><article class="card project-detail-card"><div class="card-head"><div><h2>项目阶段</h2><p>以当前有效基线判断计划与实际偏差</p></div>${status(p.baseline,'info')}</div><div class="phase-track">${['启动','需求','方案','开发','测试','上线'].map((x,i)=>`<div class="phase-item ${i<3?'done':i===3?'active':''}"><small>0${i+1}</small><b>${x}</b><small>${i<3?'已完成':i===3?'进行中':'待开始'}</small></div>`).join('')}</div><div class="card-head" style="margin-top:22px"><div><h2>执行摘要</h2><p>最近7天的关键进展与偏差</p></div></div><div class="timeline"><div class="timeline-item"><b>数据接口联调完成 18 / 24 项</b><small>今天 09:18 · 许哲 · 关联任务 RW-072301</small></div><div class="timeline-item"><b>新增交付物版本 V1.3</b><small>昨天 17:42 · 交付人员 · 已归档</small></div><div class="timeline-item"><b>基线变更 V2 生效</b><small>07-18 16:08 · 审批通过 · 原基线保留</small></div></div></article><aside class="card project-detail-card"><div class="card-head"><div><h2>项目责任</h2><p>成员、角色和部门承诺</p></div></div><div class="project-member-list">${[['陈浩','项目负责人','技术交付中心'],['许哲','项目经理','技术交付中心'],['周启明','培训讲师','讲师部'],['王洋','商务责任人','市场销售中心']].map(x=>`<div class="project-member"><span><span class="source-icon">${x[0][0]}</span><span><b>${x[0]} · ${x[1]}</b><small>${x[2]}</small></span></span>${status('已确认','good')}</div>`).join('')}</div></aside></div>`}
function projectDetailMilestones(p){const rows=[['需求蓝图确认','07-02','07-02','已完成','0天'],['方案与原型确认','07-12','07-14','已完成','+2天'],['系统联调','07-25','07-27','进行中','预计+2天'],['内部验收','08-12','—','待开始','—'],['上线交付','08-20','—','待开始','—']];return `<article class="card data-card"><div class="card-head card-pad" style="margin:0"><div><h2>里程碑与基线偏差</h2><p>${p.baseline} · 所有计划变更保留历史版本</p></div><button class="button" data-action="project-baseline">申请基线变更</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>里程碑</th><th>计划完成</th><th>实际 / 预计</th><th>状态</th><th>偏差</th></tr></thead><tbody>${rows.map(r=>`<tr><td><b>${r[0]}</b></td><td>${r[1]}</td><td>${r[2]}</td><td>${status(r[3],r[3]==='已完成'?'good':r[3]==='进行中'?'info':'')}</td><td class="${r[4].startsWith('+')?'metric-bad':''}">${r[4]}</td></tr>`).join('')}</tbody></table></div><div class="table-footer"><span>计划日期来自当前有效基线</span><span>实际完成日期不可手工覆盖</span></div></article>`}
function projectDetailTasks(p){const taskRows=projectTasks.map((r,i)=>({r,i})).filter(({r})=>r[2]===p.name);return `<article class="card data-card"><div class="card-head card-pad" style="margin:0"><div><h2>项目任务与实际工时</h2><p>任务、工单、排期和工时使用同一编号追溯</p></div><button class="button primary" data-action="new-project-task">＋ 新建任务</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>项目任务</th><th>责任人 / 部门</th><th>截止日期</th><th>计划 / 实际工时</th><th>关联协作</th><th>状态</th></tr></thead><tbody>${taskRows.length?taskRows.map(({r,i})=>`<tr data-project-task="${i}"><td><div class="entity"><span class="entity-icon">${r[0].slice(-2)}</span><span><b>${r[1]}</b><small>${r[0]}</small></span></div></td><td><b>${r[3]}</b><br><small>${r[4]}</small></td><td>${r[5]}</td><td><b>${r[6]} / ${state.worklogs[i]||r[7]}h</b></td><td>${r[9]}</td><td>${status(r[8],r[8]==='已完成'?'good':r[8]==='已逾期'?'bad':r[8]==='待排期'?'warn':'info')}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty-note">当前演示数据未展开该项目任务</div></td></tr>'}</tbody></table></div></article>`}
function projectDetailRisks(){const risks=[['高','数据接口字段仍有6项未确认','可能影响系统联调完成时间','许哲 · 07-25'],['中','客户测试账号开通延迟','影响测试数据准备','王洋 · 07-24'],['中','培训讲师排期存在冲突','需在上线培训前完成协调','周启明 · 07-26']];return `<div class="project-detail-grid"><article class="card project-detail-card"><div class="card-head"><div><h2>风险与问题</h2><p>按客户影响和交付影响排序</p></div>${status('3项未关闭','bad')}</div><div class="risk-list">${risks.map(r=>`<div class="risk-item"><span class="risk-level">${r[0]}</span><span><b>${r[1]}</b><small>${r[2]}</small></span><span>${r[3]}</span></div>`).join('')}</div></article><aside class="card project-detail-card"><div class="card-head"><div><h2>变更记录</h2><p>原计划与审批轨迹完整保留</p></div></div><div class="timeline"><div class="timeline-item"><b>BG-260718 · 基线V2</b><small>系统联调顺延2天 · 已批准</small></div><div class="timeline-item"><b>BG-260709 · 需求范围调整</b><small>新增2个数据接口 · 已批准</small></div></div></aside></div>`}
function projectDetailAcceptance(){return `<div class="project-detail-grid"><article class="card project-detail-card"><div class="card-head"><div><h2>内部验收检查</h2><p>由公司内部确认交付完整性，不直接向客户发起</p></div>${status('待组织','warn')}</div><div class="acceptance-checklist">${[['交付物版本完整','16 / 18项'],['测试与缺陷记录','已归档'],['项目工时填报','缺失2条'],['风险与遗留问题','3项未关闭'],['财务核对','等待确认']].map((x,i)=>`<div class="acceptance-row"><span>${i<2?'✓':'!'}</span><b>${x[0]}</b>${status(x[1],i<2?'good':'warn')}</div>`).join('')}</div></article><aside class="card project-detail-card"><div class="card-head"><div><h2>验收与收尾路径</h2><p>内部验收通过后才能进入结项</p></div></div><div class="timeline"><div class="timeline-item"><b>提交内部验收申请</b><small>项目负责人整理交付包</small></div><div class="timeline-item"><b>组织内部验收</b><small>指定验收人核对成果</small></div><div class="timeline-item"><b>关闭遗留问题</b><small>明确责任人和计划</small></div><div class="timeline-item"><b>财务核对与项目结项</b><small>完成复盘和归档</small></div></div><button class="button primary" data-action="project-acceptance" style="width:100%;margin-top:16px">发起内部验收</button></aside></div>`}
function projectDetailPage(){const p=currentCompleteProject(),tabs=[['overview','项目总览'],['milestones','里程碑与计划'],['tasks','任务与工时'],['risks','风险与变更'],['acceptance','内部验收']];const panel=state.projectDetailTab==='milestones'?projectDetailMilestones(p):state.projectDetailTab==='tasks'?projectDetailTasks(p):state.projectDetailTab==='risks'?projectDetailRisks():state.projectDetailTab==='acceptance'?projectDetailAcceptance():projectDetailOverview(p);return `<div class="project-detail-shell"><div class="project-detail-head"><div><button class="button" data-project-detail-back>← 返回项目组合</button><div class="project-detail-title"><span class="project-detail-mark">${p.name[0]}</span><div><h1>${p.name}</h1><p>${p.id} · ${p.customer} · ${p.type} · 负责人 ${p.owner}</p></div></div></div><div class="project-detail-actions">${status(p.health,p.health==='正常'?'good':p.health==='需关注'?'warn':'bad')}<button class="button primary" data-project-update="${state.projectDetailIndex}">更新进度</button></div></div><div class="project-detail-tabs">${tabs.map(t=>`<button class="tab ${state.projectDetailTab===t[0]?'active':''}" data-project-detail-tab="${t[0]}">${t[1]}</button>`).join('')}</div>${detailKpis(p)}${panel}</div>`}

const projectListPageBase=pages.projects;
pages.projects=function(){return state.projectDetailIndex===null?projectListPageBase():projectDetailPage()};

function openProject(i){const p=completeProjects[i],progress=state.projectDetailProgress[i]??p.progress;openDrawer('项目详情',p.name,`<div class="detail-section"><h3>执行摘要</h3><div class="detail-grid"><div class="detail-cell"><small>总体进度</small><b>${progress}%</b></div><div class="detail-cell"><small>健康度</small><b>${p.health}</b></div><div class="detail-cell"><small>当前基线</small><b>${p.baseline}</b></div><div class="detail-cell"><small>未关闭风险</small><b>${p.risks}项</b></div></div></div><div class="detail-section"><h3>最近动态</h3><div class="timeline"><div class="timeline-item"><b>里程碑进度已更新</b><small>今天 09:18 · 项目经理</small></div><div class="timeline-item"><b>新增交付物版本 V1.3</b><small>昨天 17:42 · 交付人员</small></div><div class="timeline-item"><b>项目风险完成复核</b><small>昨天 14:05 · 项目负责人</small></div></div></div>`,`<button class="button" id="viewCompleteProject">查看完整项目</button><button class="button primary" id="updateProjectProgress">更新进度</button>`);$('#viewCompleteProject').onclick=()=>{closeDrawer();state.projectDetailIndex=i;state.projectDetailTab='overview';render('projects')};$('#updateProjectProgress').onclick=()=>{closeDrawer();projectProgressModal(i)}}
function projectProgressModal(i){const p=completeProjects[i],current=state.projectDetailProgress[i]??p.progress;showModal('项目进度',`更新 ${p.name}`,section(1,'本次进展',`<div class="project-update-summary"><div><small>当前进度</small><b>${current}%</b></div><div><small>当前阶段</small><b>${p.stage}</b></div><div><small>有效基线</small><b>${p.baseline.split(' · ')[0]}</b></div></div><div class="form-grid" style="margin-top:14px"><div class="field"><label>本次证据化进度 <em>*</em></label><input id="projectProgressValue" type="number" min="${current}" max="100" value="${Math.min(100,current+4)}"></div><div class="field"><label>进度日期 <em>*</em></label><input type="date" value="2026-07-23"></div><div class="field full"><label>进展说明 <em>*</em></label><textarea id="projectProgressNote">已完成数据接口联调新增4项，相关任务和测试结果已归档。</textarea></div></div>`)+section(2,'事实依据',`<div class="health-list"><div class="health-row"><span>✓ 项目任务</span><b>关联2项已完成任务</b></div><div class="health-row"><span>✓ 交付物</span><b>新增版本V1.3</b></div><div class="health-row"><span>ⓘ 系统校验</span><b>不允许填写无依据百分比</b></div></div>`),'<button class="button" value="cancel">取消</button><button class="button primary" id="confirmProjectProgress">提交进度</button>');$('#confirmProjectProgress').onclick=e=>{e.preventDefault();const value=Number($('#projectProgressValue').value),note=$('#projectProgressNote').value.trim();if(!value||value<current||value>100||!note)return toast('进度信息不完整','进度不能低于当前值或高于100%，并需填写事实说明。');state.projectDetailProgress[i]=value;$('#modal').close();if(state.projectDetailIndex===i)render('projects');toast('项目进度已更新',`${p.name}已更新为${value}%，任务与交付物依据已留痕。`)}}

const projectDetailBindBase=bindPage;
bindPage=function(){projectDetailBindBase();$('[data-project-detail-back]')?.addEventListener('click',()=>{state.projectDetailIndex=null;state.projectDetailTab='overview';state.projectTab='portfolio';render('projects')});$$('[data-project-detail-tab]').forEach(x=>x.onclick=()=>{state.projectDetailTab=x.dataset.projectDetailTab;render('projects')});$$('[data-project-update]').forEach(x=>x.onclick=()=>projectProgressModal(+x.dataset.projectUpdate))};
if(state.view==='projects')render('projects');
