const projectBoardItems=[
  {name:'华清咨询企业知识库',id:'PJ-260724',type:'AI产品销售',owner:'赵宁',status:'待立项',health:'条件待补',progress:0,next:'财务核验收款条件',tab:'initiation'},
  {name:'宏远集团智能客服',id:'PJ-260723',type:'AI定制开发',owner:'许哲',status:'待立项',health:'待审批',progress:0,next:'部门确认资源',tab:'initiation'},
  {name:'星河制造数据平台',id:'PJ-260718',type:'AI定制开发',owner:'陈浩',status:'执行中',health:'高风险',progress:68,next:'系统联调',detail:0},
  {name:'北辰零售账号矩阵',id:'PJ-260717',type:'自媒体代运营',owner:'林溪',status:'执行中',health:'正常',progress:42,next:'7月内容复盘',detail:1},
  {name:'嘉禾教育AI培训',id:'PJ-260716',type:'AI产品销售',owner:'周启明',status:'执行中',health:'需关注',progress:54,next:'讲师试讲',detail:2},
  {name:'瑞景文旅智能客服',id:'PJ-260715',type:'AI定制开发',owner:'许哲',status:'待内部验收',health:'正常',progress:83,next:'组织内部验收',detail:3},
  {name:'云启门店AI助手',id:'PJ-260709',type:'AI产品销售',owner:'王洋',status:'待结项',health:'需关注',progress:96,next:'财务核对',tab:'acceptance'},
  {name:'恒远集团AI训练营',id:'PJ-260628',type:'AI产品销售',owner:'周启明',status:'已完成',health:'正常',progress:100,next:'复盘已归档',tab:'acceptance'}
];
Object.assign(state,{projectBoardType:'全部业务',projectBoardSearch:''});
if(state.projectTab==='portfolio')state.projectTab='board';

function projectBoardTabs(){const tabs=[['board','项目看板'],['portfolio','项目组合'],['initiation','商务交接与立项'],['plan','计划与偏差'],['tasks','任务与工时'],['department','部门监控'],['acceptance','内部验收与收尾']];return `<div class="tabs project-tabs">${tabs.map(t=>`<button class="tab ${state.projectTab===t[0]?'active':''}" data-project-tab="${t[0]}">${t[1]}</button>`).join('')}</div>`}
function projectBoardStatus(statusName){return status(statusName,statusName==='已完成'?'good':statusName==='待内部验收'||statusName==='待结项'?'warn':statusName==='执行中'?'info':'')}
function projectBoardCard(item,index){const riskTone=item.health==='高风险'?'bad':item.health==='需关注'||item.health==='条件待补'?'warn':item.health==='正常'?'good':'info';return `<button class="project-board-card" data-project-board-card="${index}"><span class="project-board-card-top"><small>${item.id}</small>${status(item.health,riskTone)}</span><h3>${item.name}</h3><small>${item.type} · 负责人 ${item.owner}</small><span class="project-board-card-progress"><span class="progress-track"><span class="progress-fill" style="width:${item.progress}%"></span></span><b>${item.progress}%</b></span><span class="project-board-card-meta"><span>下一节点</span><b>${item.next}</b></span></button>`}
function projectBoardPanel(){
  const columns=[['待立项',2,'var(--ink-3)'],['执行中',24,'var(--accent)'],['待内部验收',3,'var(--warn)'],['待结项',2,'#8b6a2b'],['已完成',18,'var(--up)']];
  const query=state.projectBoardSearch.trim().toLowerCase(),type=state.projectBoardType;
  const filtered=projectBoardItems.map((item,index)=>({item,index})).filter(({item})=>(type==='全部业务'||item.type===type)&&(!query||`${item.name}${item.id}${item.owner}${item.next}`.toLowerCase().includes(query)));
  return `<div class="project-board-shell"><section class="project-board-summary"><article class="project-board-stat"><small>本期项目</small><strong>32</strong><span>覆盖三类主营业务</span></article><article class="project-board-stat"><small>执行中</small><strong>24</strong><span>本周新增2项</span></article><article class="project-board-stat"><small>进度偏差</small><strong style="color:var(--down)">4</strong><span>超过当前基线</span></article><article class="project-board-stat"><small>待内部验收</small><strong>3</strong><span>最长等待4天</span></article><article class="project-board-stat"><small>待负责人介入</small><strong style="color:var(--warn)">5</strong><span>风险、工时或排期异常</span></article></section><div class="project-board-toolbar"><div class="project-board-filters"><input class="control search" id="projectBoardSearch" value="${esc(state.projectBoardSearch)}" placeholder="搜索项目、编号、负责人"><select class="select" id="projectBoardType"><option ${type==='全部业务'?'selected':''}>全部业务</option><option ${type==='AI产品销售'?'selected':''}>AI产品销售</option><option ${type==='AI定制开发'?'selected':''}>AI定制开发</option><option ${type==='自媒体代运营'?'selected':''}>自媒体代运营</option></select></div><div class="board-legend"><span><i style="background:var(--down)"></i>高风险</span><span><i style="background:var(--warn)"></i>需关注</span><span><i style="background:var(--up)"></i>正常</span></div></div><div class="project-kanban-scroll"><section class="project-kanban">${columns.map(col=>{const rows=filtered.filter(({item})=>item.status===col[0]);return `<article class="project-kanban-column"><div class="project-kanban-head"><span><i style="background:${col[2]}"></i><b>${col[0]}</b></span><em>${col[1]}项</em></div><div class="project-board-cards">${rows.length?rows.map(({item,index})=>projectBoardCard(item,index)).join(''):'<div class="project-board-empty">当前筛选条件下无项目</div>'}${col[1]>rows.length&&!query&&type==='全部业务'?`<span class="project-board-more">另有 ${col[1]-rows.length} 个项目未展开</span>`:''}</div></article>`}).join('')}</section></div></div>`
}
function pageProjectBoard(){return head('项目交付','从总项目看板掌握全部项目状态，再下钻立项、计划、任务、内部验收、结项与复盘。','<button class="button">交付模板</button>')+projectBoardTabs()+projectBoardPanel()}

const projectPagesWithDetail=pages.projects;
pages.projects=function(){
  if(state.projectDetailIndex!==null)return projectPagesWithDetail();
  if(state.projectTab==='board')return pageProjectBoard();
  return projectPagesWithDetail().replace('<div class="tabs project-tabs">','<div class="tabs project-tabs"><button class="tab" data-project-tab="board">项目看板</button>');
};

function openBoardProject(index){const item=projectBoardItems[index];if(Number.isInteger(item.detail)){state.projectDetailReturnTab='board';return openProject(item.detail)}openDrawer('项目看板',item.name,`<div class="detail-section"><div class="detail-summary">${projectBoardStatus(item.status)}<small>${item.id} · ${item.type}</small></div></div><div class="detail-section"><h3>当前摘要</h3><div class="detail-grid"><div class="detail-cell"><small>负责人</small><b>${item.owner}</b></div><div class="detail-cell"><small>健康度</small><b>${item.health}</b></div><div class="detail-cell"><small>证据化进度</small><b>${item.progress}%</b></div><div class="detail-cell"><small>下一节点</small><b>${item.next}</b></div></div></div><div class="detail-section"><h3>最近状态</h3><div class="timeline"><div class="timeline-item"><b>${item.next}</b><small>当前待处理事项 · ${item.owner}</small></div><div class="timeline-item"><b>项目状态进入${item.status}</b><small>系统按业务事实自动更新</small></div></div></div>`,`<button class="button" data-close-drawer>关闭</button><button class="button primary" id="openBoardFlow">进入对应流程</button>`);$('#openBoardFlow').onclick=()=>{closeDrawer();state.projectTab=item.tab;render('projects')}}

const projectBoardBindBase=bindPage;
bindPage=function(){projectBoardBindBase();const back=$('[data-project-detail-back]');if(back&&state.projectDetailReturnTab==='board'){back.textContent='← 返回项目看板';back.addEventListener('click',()=>{state.projectDetailReturnTab=null;state.projectTab='board';render('projects')})}$$('[data-project-board-card]').forEach(x=>x.onclick=()=>openBoardProject(+x.dataset.projectBoardCard));$('#projectBoardType')?.addEventListener('change',e=>{state.projectBoardType=e.target.value;render('projects')});$('#projectBoardSearch')?.addEventListener('change',e=>{state.projectBoardSearch=e.target.value;render('projects')});$('#projectBoardSearch')?.addEventListener('keydown',e=>{if(e.key==='Enter'){state.projectBoardSearch=e.target.value;render('projects')}})};
if(state.view==='projects')render('projects');
